### ISSUE TITLE
Ray Tracing in One Weekend — The Book Series

### ISSUE THREAD

**Issue by rainy-me** [rainy-me/zest#57]
```toml
title = "Ray Tracing in One Weekend — The Book Series"

related = [
  'https://raytracing.github.io/'
]

[[problem_or_opportunity]]
detail = '''learn ray tracing for fun
'''

[[duration]]
days = 30
# months = 0
# years = 0

[[cost]]
detail = '''
'''

[[goal]]
detail = '''
'''
```
