### ISSUE TITLE
rust based dwm-like wm

### ISSUE THREAD

**Issue by rainy-me** [rainy-me/zest#58]
```toml
title = "A new wm"

related = [
]

[[problem_or_opportunity]]
detail = '''
'''

[[duration]]
days = 0
months = 2
# years = 0

[[cost]]
detail = '''
'''

[[goal]]
detail = '''
'''
```
